package com.hybrid.orchestration.service;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Service
public class OrchestrationService {

    private final RestTemplate restTemplate;

    public OrchestrationService() {
        this(new RestTemplate());
    }

    public OrchestrationService(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    public void executeWorkflow() {
        restTemplate.postForObject(
                "http://ingestion-service:8081/api/ingest",
                Map.of("id", "orchestrated-doc-001", "title", "Orchestrated Doc", "content", "Generated by workflow", "metadata", "{}"),
                String.class
        );

        restTemplate.postForObject(
                "http://query-service:8083/search",
                Map.of("query", "orchestrated search"),
                String.class
        );

        restTemplate.postForObject(
                "http://ranking-service:8085/api/rank",
                List.of(Map.of("id", "orchestrated-doc-001", "score", 1.0)),
                String.class
        );

        restTemplate.postForObject(
                "http://fusion-service:8087/api/fusion/combine",
                Map.of("lexical", Map.of("orchestrated-doc-001", 1.0), "semantic", Map.of("orchestrated-doc-001", 0.9)),
                String.class
        );
    }
}
