from __future__ import annotations

import json
import socket
from datetime import datetime
from urllib import request

from airflow import DAG
from airflow.operators.python import PythonOperator


def post_json(url: str, payload: dict | None = None, timeout: int = 20) -> str:
    body = b""
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url=url,
        data=body if payload is not None else None,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(req, timeout=timeout) as resp:
        status = resp.getcode()
        if status < 200 or status >= 300:
            raise RuntimeError(f"request failed: {url} status={status}")
        return resp.read().decode("utf-8")


def assert_tcp(host: str, port: int, timeout: int = 5) -> None:
    with socket.create_connection((host, port), timeout=timeout):
        return


def trigger_orchestration() -> None:
    # Orchestration-service may be intentionally down in local dev.
    # Keep DAG execution useful by continuing with direct probes.
    try:
        post_json("http://orchestration-service:8089/orchestrate/trigger")
    except Exception as exc:  # pragma: no cover
        print(f"orchestration trigger skipped: {exc}")


def ingestion_probe() -> None:
    probe_id = f"airflow-probe-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    try:
        post_json(
            "http://ingestion-service:8081/api/ingest",
            {
                "id": probe_id,
                "title": "Airflow probe document",
                "content": "Generated by Airflow DAG for batch/control-plane validation.",
                "metadata": "source=airflow;type=probe",
            },
        )
    except Exception as exc:  # pragma: no cover
        print(f"ingestion POST probe skipped: {exc}")
        assert_tcp("ingestion-service", 8081)


def query_probe() -> None:
    try:
        post_json(
            "http://query-service:8083/search",
            {
                "query": "airflow probe",
                "topK": 5,
            },
        )
    except Exception as exc:  # pragma: no cover
        print(f"query POST probe skipped: {exc}")
        assert_tcp("query-service", 8083)


with DAG(
    dag_id="hybrid_control_plane_dag",
    description="Runs scheduled orchestration and lightweight end-to-end probes.",
    start_date=datetime(2026, 1, 1),
    schedule="0 */6 * * *",
    catchup=False,
    tags=["hybrid", "control-plane", "airflow"],
) as dag:
    task_orchestrate = PythonOperator(
        task_id="trigger_orchestration_flow",
        python_callable=trigger_orchestration,
    )

    task_ingestion_probe = PythonOperator(
        task_id="ingestion_probe",
        python_callable=ingestion_probe,
    )

    task_query_probe = PythonOperator(
        task_id="query_probe",
        python_callable=query_probe,
    )

    task_orchestrate >> task_ingestion_probe >> task_query_probe
