#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "$REPO_ROOT"

VALIDATE_TARGET_DOCS="${VALIDATE_TARGET_DOCS:-5000}" \
VALIDATE_LOAD_CONCURRENCY="${VALIDATE_LOAD_CONCURRENCY:-20}" \
VALIDATE_BENCH_REQUESTS="${VALIDATE_BENCH_REQUESTS:-60}" \
VALIDATE_BENCH_CONCURRENCY="${VALIDATE_BENCH_CONCURRENCY:-10}" \
VALIDATE_BENCH_RATE_QPS="${VALIDATE_BENCH_RATE_QPS:-8}" \
make validate-500k-paced-smoke
